
@Library('devops-shared-library') _

pipeline {
    agent any

    environment {
        ENV="dev"
    }

    stages {

        stage('Checkout'){
            steps{
                git 'https://github.com/org/infra-codebase.git'
            }
        }

        stage('Deploy Infrastructure'){
            steps{
                script{
                    terraformPipeline.run(env.ENV)
                }
            }
        }
    }
}
